### ISSUE TITLE
[Envoy] binding causing NPE

### ISSUE THREAD

**Issue by lsiepel** [HentschelT/openhab2-addons#27]
When starting openhab 2.5.0 build 1564 i get an NPE:
```2019-03-30 21:04:46.624 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NullPointerException: null
	at org.openhab.binding.enphaseenvoy.discovery.EnphaseEnvoyDiscoveryService.scanForInverterThings(EnphaseEnvoyDiscoveryService.java:121) ~[?:?]
	at org.openhab.binding.enphaseenvoy.discovery.EnphaseEnvoyDiscoveryService.startScan(EnphaseEnvoyDiscoveryService.java:90) ~[?:?]
	at org.openhab.binding.enphaseenvoy.discovery.EnphaseEnvoyDiscoveryService$1.run(EnphaseEnvoyDiscoveryService.java:43) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]```

**Comment by lsiepel** [comment]
Still happening with 2.5.0. build 1601
`2019-05-26 22:53:25.743 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NullPointerException: null
	at org.openhab.binding.enphaseenvoy.discovery.EnphaseEnvoyDiscoveryService.scanForInverterThings(EnphaseEnvoyDiscoveryService.java:121) ~[?:?]
	at org.openhab.binding.enphaseenvoy.discovery.EnphaseEnvoyDiscoveryService.startScan(EnphaseEnvoyDiscoveryService.java:90) ~[?:?]
	at org.openhab.binding.enphaseenvoy.discovery.EnphaseEnvoyDiscoveryService$1.run(EnphaseEnvoyDiscoveryService.java:43) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]`

**Comment by lsiepel** [comment]
They are gone after OH2.5 M2
